### ISSUE TITLE
Request for new npm package version 

### ISSUE THREAD

**Issue by 1rahulr** [joeledwards/node-cassandra-migration#12]
Please release a new version so that cassandra-migration can be used with cassandra version 4.x

**Comment by joeledwards** [comment]
Good morning, thank you for the request. Let me see what is involved here.

I haven't worked with Cassandra for some time. You are also welcome to submit a PR if I am not moving fast enough on this.

**Comment by 1rahulr** [comment]
https://github.com/joeledwards/node-cassandra-migration/pull/11 has changes needed. Please release a new version at  https://www.npmjs.com/package/cassandra-migration which includes this change.

**Comment by ruettenm** [comment]
@joeledwards let's close this issue because the pull request was merged?
