### ISSUE TITLE
Ability to use user credentials

### ISSUE THREAD

**Issue by michajas** [joeledwards/node-cassandra-migration#2]
It would be nice to have ability to use user credentials to login to cassandra database to perform schema migrations. I can't find a way to pass authenticator object to json settings file.

**Comment by joeledwards** [comment]
I have added support for simple credentials (username + password) in a new "auth" field in the configuration file (outside of the cassandra field). Please let me know if this is sufficient for now.

I hope to provide a more full-featured auth-mechanism in the future.
